version: '3.4'

services:
  rjsilvas.myfinances:
    image: ${DOCKER_REGISTRY-}rjsilvasmyfinances
    container_name: webapi
    build:
      context: .      
      dockerfile: src/Backend/Services/MyFinances/RJSilvas.MyFinances.WebAPI/Dockerfile      
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mysql:8.0.22
    container_name: mysqldb
    ports:
        - "3306:3306"
    expose: 
        - 3306
    volumes:
        - ./data/MyFinances/init.sql:/docker-entrypoint-initdb.d/init.sql
        - db-volume:/var/lib/mysql
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: admin
        
volumes:
  db-volume: